
'use server';

/**
 * @fileOverview A Genkit flow to summarize the weather for a given location.
 *
 * - summarizeWeather - A function that returns a weather summary and icon.
 * - SummarizeWeatherInput - The input type for the summarizeWeather function.
 * - SummarizeWeatherOutput - The return type for the summarizeWeather function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

const SummarizeWeatherInputSchema = z.object({
  latitude: z.number().describe('The latitude for the weather forecast.'),
  longitude: z.number().describe('The longitude for the weather forecast.'),
  language: z.string().describe('The language for the weather summary.'),
});

export type SummarizeWeatherInput = z.infer<typeof SummarizeWeatherInputSchema>;

const DailyForecastSchema = z.object({
    day: z.string().describe("The day of the week (e.g., 'Monday')."),
    icon: z.enum(["Sun", "CloudSun", "Cloud", "Rain", "Snow"]).describe('An icon name that best represents the weather conditions for the day.'),
    high: z.number().describe('The high temperature for the day in Celsius.'),
    low: z.number().describe('The low temperature for the day in Celsius.'),
});

const SummarizeWeatherOutputSchema = z.object({
  summary: z.string().describe('A short, descriptive summary of the current weather (e.g., "Sunny with a light breeze, perfect for a walk.").'),
  icon: z.enum(["Sun", "CloudSun", "Cloud", "Rain", "Snow"]).describe('An icon name that best represents the current weather conditions.'),
  currentTemp: z.number().describe('The current temperature in Celsius.'),
  forecast: z.array(DailyForecastSchema).describe("A 5-day weather forecast."),
});

export type SummarizeWeatherOutput = z.infer<typeof SummarizeWeatherOutputSchema>;

export async function summarizeWeather(
  input: SummarizeWeatherInput
): Promise<SummarizeWeatherOutput> {
  // In a real app, you would call a weather API here.
  // For this example, we will simulate the API call and use AI to generate a creative summary.
  const simulatedWeatherData = {
    current: {
        temperature: 22,
        condition: 'Partly Cloudy',
        windSpeed: 10,
    },
    forecast: [
        { day: "Today", high: 24, low: 18, condition: "Partly Cloudy" },
        { day: "Mon", high: 26, low: 19, condition: "Sunny" },
        { day: "Tue", high: 23, low: 17, condition: "Cloudy" },
        { day: "Wed", high: 20, low: 15, condition: "Rain" },
        { day: "Thu", high: 25, low: 18, condition: "Sunny" },
    ],
  };

  const flow = ai.defineFlow(
    {
      name: 'summarizeWeatherFlow',
      inputSchema: z.object({
        weatherData: z.any(),
        language: z.string(),
      }),
      outputSchema: SummarizeWeatherOutputSchema,
    },
    async ({ weatherData, language }) => {
      const prompt = ai.definePrompt({
        name: 'summarizeWeatherPrompt',
        output: { schema: SummarizeWeatherOutputSchema },
        prompt: `Based on the following weather data, provide a short, friendly, and descriptive summary for a hotel guest. Also suggest an appropriate icon for the current weather and for each day in the forecast.

        The summary should be in ${language}.
        
        Weather Data:
        - Current Condition: ${weatherData.current.condition}
        - Current Temperature: ${weatherData.current.temperature}°C
        - Wind Speed: ${weatherData.current.windSpeed} km/h
        - 5-Day Forecast: ${JSON.stringify(weatherData.forecast)}
        `,
      });

      const { output } = await prompt();
      // Add current temperature to the output as it's not generated by the AI
      if (output) {
        output.currentTemp = weatherData.current.temperature;
      }
      return output!;
    }
  );

  return await flow({ weatherData: simulatedWeatherData, language: input.language });
}
